apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eazepay-ingress
  namespace: eazepay
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - eazepay.com
    - app.eazepay.com
    - agent.eazepay.com
    - api.eazepay.com
    secretName: eazepay-tls
  rules:
  - host: app.eazepay.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: customer-portal
            port:
              number: 80
  - host: agent.eazepay.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: agent-portal
            port:
              number: 80
  - host: api.eazepay.com
    http:
      paths:
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: identity-service
            port:
              number: 8000
      - path: /wallet
        pathType: Prefix
        backend:
          service:
            name: wallet-service
            port:
              number: 8003
      - path: /transactions
        pathType: Prefix
        backend:
          service:
            name: transaction-service
            port:
              number: 8002
